apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-keycloak-postgresql-0
spec:
  storageClassName: ""
  claimRef:
    name: data-keycloak-postgresql-0
    namespace: keycloak
  capacity:
   storage: 8Gi
  accessModes:
   - ReadWriteOnce
  hostPath:
    path: "/mnt/"